export const MOCK_CALENDAR = [
  { id: 1, title: 'Convocatoria a Elecciones Generales 2026', date: '2025-03-26', description: 'Convocatoria oficial confirmada por JNE - Resolución publicada', source_url: 'https://portal.jne.gob.pe/portal', parsed_hash: 'hash-conv-2026', type: 'convocatoria' },
  { id: 2, title: 'Elecciones Generales 2026', date: '2026-04-12', description: 'Domingo electoral CONFIRMADO - Votación para Presidente, Vicepresidentes, 60 Senadores, 130 Diputados y 5 representantes al Parlamento Andino. Horario: 7:00 AM - 5:00 PM. Más de 27 millones de electores', source_url: 'https://eg2026.onpe.gob.pe', parsed_hash: 'hash-eg-2026', type: 'eleccion' },
  { id: 3, title: 'Elecciones Primarias - Partidos Políticos', date: '2025-12-01', description: 'Proceso de elecciones primarias de organizaciones políticas inscritas: Fuerza Popular, Perú Libre, Acción Popular, Partido Morado, Podemos Perú, APP', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales', parsed_hash: 'hash-primarias-2025', type: 'primarias' },
  { id: 4, title: 'Conformación de 14 ODPE', date: '2025-09-09', description: 'ONPE confirma conformación de 14 Oficinas Descentralizadas de Procesos Electorales para organizar las Elecciones Primarias - RJ-141-2025-JN', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7141561-rj-141-2025-jn', parsed_hash: 'hash-odpe-2025', type: 'organizacion' },
  { id: 5, title: 'Implementación Voto Digital - Grupos Prioritarios', date: '2025-04-30', description: 'ONPE establece grupos prioritarios para voto digital según Ley N° 32270 - RJ-69-2025-JN y RJ-93-2025-JN', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/6727470-rj-69-2025-jn', parsed_hash: 'hash-voto-dig-2025', type: 'tecnologia' },
  { id: 6, title: 'Aprobación Catálogo Materiales Electorales', date: '2025-09-01', description: 'ONPE aprueba Catálogo de Materiales Electorales Voto Convencional v0.1 - RJ-140-2025-JN', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7103916-rj-140-2025-jn', parsed_hash: 'hash-materiales-2025', type: 'organizacion' },
  { id: 7, title: 'Conformación Comité de Gerencia EG 2026', date: '2025-03-31', description: 'ONPE conforma Comité de Gerencia para las Elecciones Generales 2026 - RJ-45-2025-JN', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/6621611-rj-45-2025-jn', parsed_hash: 'hash-comite-2025', type: 'organizacion' },
  { id: 8, title: 'JNE: Conformación de Jurados Electorales Especiales', date: '2025-09-28', description: 'JNE declara conformación de Jurados Electorales Especiales para Elecciones Generales 2026', source_url: 'https://portal.jne.gob.pe/Portal/Pagina/Nota/18878', parsed_hash: 'hash-jee-2025', type: 'organizacion' }
]

export const MOCK_CANDIDATES = [
  // Candidatos Presidenciales Elecciones Generales 2026 - Planchas inscritas
  { id: 1, name: 'Ana Lucía Vargas', party: 'Fuerza Popular', role: 'Presidente', bio: 'Abogada especialista en derecho constitucional. Ex Congresista 2021-2026.', photo_url: '/photos/ana_vargas.jpg', cv_url: '/docs/ana_vargas_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/ana_vargas', parsed_hash: 'hash-cand-pres-1', proposals: [ {sector:'Economía', title:'Reactivación Económica Post-Pandemia', description:'Plan integral para dinamizar la economía nacional con enfoque en sectores productivos.'}, {sector:'Seguridad', title:'Reforma del Sistema de Justicia', description:'Fortalecimiento de instituciones y lucha contra la corrupción.'}, {sector:'Educación', title:'Universidad Gratuita', description:'Acceso gratuito a educación superior pública de calidad.'} ], activities: [ {date:'2025-11-15', title:'Presentación de plan de gobierno en Lima'}, {date:'2025-11-20', title:'Gira por región Cusco'} ] },
  { id: 2, name: 'Carlos Mendoza', party: 'Perú Libre', role: 'Presidente', bio: 'Economista, ex Ministro de Economía. Especialista en políticas sociales.', photo_url: '/photos/carlos_mendoza.jpg', cv_url: '/docs/carlos_mendoza_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/carlos_mendoza', parsed_hash: 'hash-cand-pres-2', proposals: [ {sector:'Economía', title:'Nueva Constitución Económica', description:'Modelo económico con mayor participación del Estado en sectores estratégicos.'}, {sector:'Salud', title:'Sistema Nacional de Salud', description:'Salud gratuita y universal para todos los peruanos.'}, {sector:'Minería', title:'Renegociación de Contratos Mineros', description:'Mayor regalías para el Estado de la explotación de recursos naturales.'} ], activities: [ {date:'2025-11-18', title:'Debate en Universidad San Marcos'}, {date:'2025-11-25', title:'Rally en Plaza de Armas - Arequipa'} ] },
  { id: 3, name: 'Roberto Silva', party: 'Acción Popular', role: 'Presidente', bio: 'Ingeniero civil, ex Alcalde de Lima Metropolitana. Experiencia en gestión pública.', photo_url: '/photos/roberto_silva.jpg', cv_url: '/docs/roberto_silva_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/roberto_silva', parsed_hash: 'hash-cand-pres-3', proposals: [ {sector:'Infraestructura', title:'Programa Nacional de Infraestructura', description:'Modernización de carreteras, puertos y aeropuertos para conectar el país.'}, {sector:'Descentralización', title:'Fortalecimiento Regional', description:'Transferencia de competencias y recursos a gobiernos regionales.'}, {sector:'Agricultura', title:'Tecnificación del Agro', description:'Modernización del sector agrícola con tecnología e irrigación.'} ], activities: [ {date:'2025-11-22', title:'Presentación de propuestas en CIP'}, {date:'2025-11-28', title:'Visita a agricultores en Ica'} ] },
  { id: 4, name: 'Elena Morales', party: 'Renovación Popular', role: 'Presidente', bio: 'Empresaria y economista. Ex presidenta de CONFIEP. Defensora del libre mercado.', photo_url: '/photos/elena_morales.jpg', cv_url: '/docs/elena_morales_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/elena_morales', parsed_hash: 'hash-cand-pres-4', proposals: [ {sector:'Economía', title:'Liberalización Económica', description:'Reducción de barreras burocráticas y promoción de la inversión privada.'}, {sector:'Empleo', title:'Flexibilización Laboral', description:'Modernización del código laboral para generar más empleo formal.'}, {sector:'Corrupción', title:'Transparencia Total', description:'Digitalización de procesos públicos y auditorías permanentes.'} ], activities: [ {date:'2025-11-16', title:'Foro empresarial en CCL'}, {date:'2025-11-24', title:'Gira por el norte del país'} ] },
  // Candidatos al Senado - Muestra representativa
  { id: 5, name: 'Patricia Ramos', party: 'Renovación Popular', role: 'Senador', region: 'Lima', bio: 'Abogada constitucionalista, ex presidenta del Colegio de Abogados de Lima.', photo_url: '/photos/patricia_ramos.jpg', cv_url: '/docs/patricia_ramos_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/patricia_ramos', parsed_hash: 'hash-cand-sen-1', proposals: [ {sector:'Justicia', title:'Reforma Judicial Integral', description:'Modernización del Poder Judicial y fortalecimiento del Ministerio Público.'} ], activities: [ {date:'2025-11-19', title:'Foro sobre reforma judicial'} ] },
  { id: 6, name: 'Jorge Huamán', party: 'Perú Libre', role: 'Senador', region: 'Cusco', bio: 'Profesor universitario, especialista en desarrollo rural y políticas agrarias.', photo_url: '/photos/jorge_huaman.jpg', cv_url: '/docs/jorge_huaman_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/jorge_huaman', parsed_hash: 'hash-cand-sen-2', proposals: [ {sector:'Agricultura', title:'Reforma Agraria Integral', description:'Redistribución de tierras y apoyo técnico a pequeños productores.'} ], activities: [ {date:'2025-11-17', title:'Asamblea de comunidades campesinas'} ] },
  // Candidatos a Diputados - Muestra representativa 
  { id: 7, name: 'Miguel Torres', party: 'Alianza para el Progreso', role: 'Diputado', region: 'La Libertad', bio: 'Médico cirujano, especialista en salud pública. Ex director regional de salud.', photo_url: '/photos/miguel_torres.jpg', cv_url: '/docs/miguel_torres_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/miguel_torres', parsed_hash: 'hash-cand-dip-1', proposals: [ {sector:'Salud', title:'Hospitales de Alta Complejidad', description:'Red nacional de hospitales especializados en cada región.'} ], activities: [ {date:'2025-11-21', title:'Campaña de salud preventiva'} ] },
  { id: 8, name: 'Carmen Solís', party: 'Fuerza Popular', role: 'Diputado', region: 'Arequipa', bio: 'Ingeniera industrial, especialista en gestión empresarial y desarrollo económico.', photo_url: '/photos/carmen_solis.jpg', cv_url: '/docs/carmen_solis_cv.pdf', source_url: 'https://portal.jne.gob.pe/candidatos/carmen_solis', parsed_hash: 'hash-cand-dip-2', proposals: [ {sector:'Industria', title:'Parques Industriales Regionales', description:'Desarrollo de zonas industriales especializadas en cada región.'} ], activities: [ {date:'2025-11-23', title:'Reunión con empresarios manufactureros'} ] }
]

export const MOCK_NEWS = [
  { id: 1, titulo: 'JNE demanda partida adicional de S/ 372 millones para procesos electorales 2026', cuerpo: 'El Jurado Nacional de Elecciones (JNE) solicita presupuesto adicional de 372 millones de soles para garantizar el desarrollo de los procesos electorales de 2026, incluyendo las Elecciones Generales del 12 de abril.', fuente: 'JNE', url: 'https://portal.jne.gob.pe/Portal/Pagina/Nota/18917', publicado_en: '2025-10-01T00:00:00.000Z', source_url: 'https://portal.jne.gob.pe/portal', parsed_hash: 'hash-news-presupuesto' },
  { id: 2, titulo: 'JNE auditará solución tecnológica de ONPE para implementación del voto digital', cuerpo: 'El Jurado Nacional de Elecciones realizará auditoría a la solución tecnológica que desarrolla ONPE para la implementación del voto digital en las Elecciones Generales 2026, garantizando transparencia y seguridad.', fuente: 'JNE', url: 'https://portal.jne.gob.pe/Portal/Pagina/Nota/118895', publicado_en: '2025-09-29T00:00:00.000Z', source_url: 'https://portal.jne.gob.pe/portal', parsed_hash: 'hash-news-auditoria-digital' },
  { id: 3, titulo: 'ONPE conforma 14 ODPE para organizar Elecciones Primarias de las EG 2026', cuerpo: 'La ONPE oficializa la conformación de catorce Oficinas Descentralizadas de Procesos Electorales encargadas de organizar las Elecciones Primarias de las organizaciones políticas para las Elecciones Generales 2026.', fuente: 'ONPE', url: 'https://www.gob.pe/institucion/onpe/normas-legales/7141561-rj-141-2025-jn', publicado_en: '2025-09-09T00:00:00.000Z', source_url: 'https://eg2026.onpe.gob.pe', parsed_hash: 'hash-news-odpe' },
  { id: 4, titulo: 'JNE declara conformación de Jurados Electorales Especiales para EG 2026', cuerbo: 'El Jurado Nacional de Elecciones oficializa la conformación de los Jurados Electorales Especiales que tendrán a su cargo la supervisión y resolución de controversias durante las Elecciones Generales 2026.', fuente: 'JNE', url: 'https://portal.jne.gob.pe/Portal/Pagina/Nota/18878', publicado_en: '2025-09-28T00:00:00.000Z', source_url: 'https://portal.jne.gob.pe/portal', parsed_hash: 'hash-news-jee' },
  { id: 5, titulo: 'ONPE aprueba catálogo de materiales electorales para voto convencional EG 2026', cuerpo: 'La Oficina Nacional de Procesos Electorales aprueba el "Catálogo de Materiales Electorales Voto Convencional" versión 0.1, estableciendo los materiales oficiales para las Elecciones Generales 2026 del 12 de abril.', fuente: 'ONPE', url: 'https://www.gob.pe/institucion/onpe/normas-legales/7103916-rj-140-2025-jn', publicado_en: '2025-09-01T00:00:00.000Z', source_url: 'https://eg2026.onpe.gob.pe', parsed_hash: 'hash-news-materiales' },
  { id: 6, titulo: 'Presidente del JNE toma juramento a titulares de 31 Jurados Electorales Especiales', cuerpo: 'El presidente del Jurado Nacional de Elecciones juramentó a los titulares de 31 Jurados Electorales Especiales que ejercerán funciones durante el proceso de Elecciones Generales 2026 en todo el territorio nacional.', fuente: 'JNE', url: 'https://portal.jne.gob.pe/Portal/Pagina/Nota/18916', publicado_en: '2025-10-01T00:00:00.000Z', source_url: 'https://portal.jne.gob.pe/portal', parsed_hash: 'hash-news-juramento' },
  { id: 7, titulo: 'JNE lanza plataforma "Voto Informado" para Elecciones Generales 2026', cuerpo: 'El Jurado Nacional de Elecciones presenta oficialmente la plataforma Voto Informado con información sobre las 4 autoridades a elegir: Presidente/Vicepresidentes, 130 Diputados, 60 Senadores y 5 representantes al Parlamento Andino. Incluye cronograma electoral actualizado.', fuente: 'JNE', url: 'https://votoinformado.jne.gob.pe/voto', publicado_en: '2025-11-15T00:00:00.000Z', source_url: 'https://votoinformado.jne.gob.pe', parsed_hash: 'hash-news-voto-informado' },
  { id: 8, titulo: 'InfoGob JNE: Base de datos electoral más completa del país disponible', cuerpo: 'El Observatorio para la Gobernabilidad del JNE pone a disposición la base de datos electoral más completa del Perú, con información de políticos, partidos y elecciones desde 1931. Incluye herramientas de análisis y reportes especializados.', fuente: 'JNE', url: 'https://infogob.jne.gob.pe', publicado_en: '2025-11-10T00:00:00.000Z', source_url: 'https://infogob.jne.gob.pe', parsed_hash: 'hash-news-infogob' }
]

export const MOCK_PARTIES = [
  { id: 1, name: 'Fuerza Popular', abbreviation: 'FP', description: 'Partido político inscrito para EG 2026. Realizó elecciones primarias confirmadas por ONPE (RG-13-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/fuerza_popular.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7169059-rg-13-2025-goecor', parsed_hash: 'hash-party-fp', primary_status: 'confirmada', primary_mode: 'delegados' },
  { id: 2, name: 'Perú Libre', abbreviation: 'PL', description: 'Partido Político Nacional Perú Libre inscrito para EG 2026. Elecciones primarias confirmadas por ONPE (RG-42-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/peru_libre.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7201382-rg-42-2025-goecor', parsed_hash: 'hash-party-pl', primary_status: 'confirmada', primary_mode: 'delegados' },
  { id: 3, name: 'Acción Popular', abbreviation: 'AP', description: 'Partido inscrito para EG 2026. Elecciones primarias confirmadas por ONPE (RG-4-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/accion_popular.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7169041-rg-4-2025-goecor', parsed_hash: 'hash-party-ap', primary_status: 'confirmada', primary_mode: 'delegados' },
  { id: 4, name: 'Partido Morado', abbreviation: 'PM', description: 'Partido inscrito para EG 2026. Elecciones primarias confirmadas por ONPE (RG-47-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/partido_morado.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7285885-rg-47-2025-goecor', parsed_hash: 'hash-party-pm', primary_status: 'confirmada', primary_mode: 'delegados' },
  { id: 5, name: 'Podemos Perú', abbreviation: 'PP', description: 'Partido inscrito para EG 2026. Elecciones primarias confirmadas por ONPE (RG-15-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/podemos_peru.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7169061-rg-15-2025-goecor', parsed_hash: 'hash-party-pp', primary_status: 'confirmada', primary_mode: 'delegados' },
  { id: 6, name: 'Partido Aprista Peruano', abbreviation: 'PAP', description: 'Partido Aprista Peruano inscrito para EG 2026. Elecciones primarias confirmadas por ONPE (RG-26-2025-GOECOR). Modalidad: afiliados', logo_url: '/logos/partido_aprista.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7169079-rg-26-2025-goecor', parsed_hash: 'hash-party-pap', primary_status: 'confirmada', primary_mode: 'afiliados' },
  { id: 7, name: 'Alianza Unidad Nacional', abbreviation: 'AUN', description: 'Alianza electoral inscrita para EG 2026. Elecciones primarias confirmadas por ONPE (RG-34-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/alianza_unidad.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7169095-rg-34-2025-goecor', parsed_hash: 'hash-party-aun', primary_status: 'confirmada', primary_mode: 'delegados' },
  { id: 8, name: 'Ciudadanos por el Perú', abbreviation: 'CPP', description: 'Partido Ciudadanos por el Perú inscrito para EG 2026. Elecciones primarias confirmadas por ONPE (RG-37-2025-GOECOR). Modalidad: delegados', logo_url: '/logos/ciudadanos_peru.png', source_url: 'https://www.gob.pe/institucion/onpe/normas-legales/7188610-rg-37-2025-goecor', parsed_hash: 'hash-party-cpp', primary_status: 'confirmada', primary_mode: 'delegados' }
]

export const OFFICIAL_JNE_PLATFORMS = [
  {
    id: 1,
    name: 'Plataforma Electoral JNE',
    url: 'https://plataformaelectoral.jne.gob.pe',
    description: 'Consulta de expedientes, candidatos, planes de gobierno, resoluciones y audiencias electorales',
    services: ['Búsqueda de candidatos', 'Planes de gobierno', 'Expedientes electorales', 'Resoluciones JNE', 'Programación de audiencias'],
    category: 'procesos_electorales'
  },
  {
    id: 2,
    name: 'InfoGob - Observatorio para la Gobernabilidad',
    url: 'https://infogob.jne.gob.pe',
    description: 'Base de datos completa de información político-electoral desde 1931',
    services: ['Información de políticos', 'Base de datos de partidos', 'Resultados electorales históricos', 'Análisis electoral', 'Reportes y boletines'],
    category: 'informacion_historica'
  },
  {
    id: 3,
    name: 'Voto Informado JNE',
    url: 'https://votoinformado.jne.gob.pe/voto',
    description: 'Portal oficial para ejercer un voto informado en las Elecciones Generales 2026',
    services: ['Cronograma electoral', 'Autoridades a elegir', 'Liga de la Democracia', 'Igualdad Política', 'JNE Fact Checking'],
    category: 'educacion_electoral',
    countdown: 'Faltan 147 días para las EG 2026'
  },
  {
    id: 4,
    name: 'Registro de Organizaciones Políticas',
    url: 'https://sroppublico.jne.gob.pe/Consulta/OrganizacionPolitica',
    description: 'Directorio oficial de organizaciones políticas registradas ante el JNE',
    services: ['Búsqueda de partidos políticos', 'Estado de organizaciones', 'Datos de contacto', 'Tipo y ámbito'],
    category: 'organizaciones_politicas'
  }
]

export const MOCK_POLLING_STATIONS = [
  { id: 1, name: 'I.E. Ricardo Palma', address: 'Jr. Huancavelica 485, Cercado de Lima', lat: -12.0464, lng: -77.0428, district:'Lima', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: true, contact: '01-315-0000', mesas: ['Mesa 001A', 'Mesa 002A', 'Mesa 003A'], capacity: 300 },
  { id: 2, name: 'Universidad Mayor de San Marcos', address: 'Av. Venezuela s/n, Lima', lat: -12.0580, lng: -77.0814, district:'Lima', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: true, contact: '01-619-7000', mesas: ['Mesa 010A', 'Mesa 011A', 'Mesa 012A', 'Mesa 013A'], capacity: 500 },
  { id: 3, name: 'I.E. Mercedes Cabello de Carbonera', address: 'Jr. Ica 336, Lima', lat: -12.0490, lng: -77.0350, district:'Lima', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: false, contact: '01-427-5500', mesas: ['Mesa 025B', 'Mesa 026B'], capacity: 200 },
  { id: 4, name: 'Colegio Salesiano San Juan Bosco', address: 'Jr. Nazca 852, Breña', lat: -12.0580, lng: -77.0510, district:'Breña', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: true, contact: '01-424-8989', mesas: ['Mesa 040C', 'Mesa 041C', 'Mesa 042C'], capacity: 350 },
  { id: 5, name: 'I.E. José Carlos Mariátegui', address: 'Av. Colonial 1520, Callao', lat: -12.0640, lng: -77.1280, district:'Callao', province:'Callao', region:'Callao', hours: '07:00-17:00', accessibility: true, contact: '01-429-8750', mesas: ['Mesa 055D', 'Mesa 056D'], capacity: 250 },
  { id: 6, name: 'Universidad Nacional de Ingeniería', address: 'Av. Túpac Amaru 210, Rímac', lat: -12.0210, lng: -77.0490, district:'Rímac', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: true, contact: '01-481-1070', mesas: ['Mesa 070E', 'Mesa 071E', 'Mesa 072E', 'Mesa 073E'], capacity: 600 },
  { id: 7, name: 'I.E. Bartolomé Herrera', address: 'Jr. Camaná 459, Lima', lat: -12.0440, lng: -77.0380, district:'Lima', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: false, contact: '01-426-5720', mesas: ['Mesa 085F', 'Mesa 086F'], capacity: 180 },
  { id: 8, name: 'Universidad Nacional Federico Villarreal', address: 'Jr. Carlos Gonzáles 285, Lima', lat: -12.0520, lng: -77.0410, district:'Lima', province:'Lima', region:'Lima', hours: '07:00-17:00', accessibility: true, contact: '01-748-0888', mesas: ['Mesa 100G', 'Mesa 101G', 'Mesa 102G'], capacity: 400 }
]

export const MOCK_VOTER_GUIDES = [
  { id: 1, title: 'Guía de la cédula de sufragio - Elecciones Generales 2026', body: 'Explicación detallada sobre cómo marcar correctamente la cédula de sufragio. Incluye las 5 elecciones: Presidente y Vicepresidentes, Senadores, Diputados, Parlamento Andino y voto preferencial. Instrucciones paso a paso con imágenes y ejemplos prácticos.', attachments: ['/docs/guia_cedula_EG2026.pdf'], language: 'es', published_at: '2025-10-15', source_url: 'https://eg2026.onpe.gob.pe/cedula', parsed_hash: 'hash-guide-cedula' },
  { id: 2, title: 'Voto Digital - Requisitos y procedimientos', body: 'Guía completa sobre el nuevo sistema de voto digital implementado según la Ley N° 32270. Incluye requisitos técnicos, población objetivo, procedimientos de seguridad y pasos para ejercer el voto electrónico desde dispositivos autorizados.', attachments: ['/docs/voto_digital_2026.pdf'], language: 'es', published_at: '2025-11-01', source_url: 'https://eg2026.onpe.gob.pe/voto-digital', parsed_hash: 'hash-guide-digital' },
  { id: 3, title: 'Elecciones Presidenciales - Proceso y autoridades', body: 'Información sobre la elección presidencial: requisitos de los candidatos, sistema de elección, eventual segunda vuelta, funciones del Presidente y Vicepresidentes electos. Incluye cronograma específico del proceso presidencial.', attachments: ['/docs/elecciones_presidenciales_2026.pdf'], language: 'es', published_at: '2025-11-05', source_url: 'https://eg2026.onpe.gob.pe/presidenciales', parsed_hash: 'hash-guide-pres' },
  { id: 4, title: 'Congreso Bicameral - Senado y Cámara de Diputados', body: 'Guía sobre el nuevo sistema bicameral: diferencias entre Senado (60 miembros) y Cámara de Diputados (130 miembros), funciones de cada cámara, sistema electoral, circunscripciones y voto preferencial para candidatos al Congreso.', attachments: ['/docs/congreso_bicameral_2026.pdf'], language: 'es', published_at: '2025-11-08', source_url: 'https://eg2026.onpe.gob.pe/congresales', parsed_hash: 'hash-guide-congreso' },
  { id: 5, title: 'Parlamento Andino - Representantes peruanos', body: 'Información sobre la elección de 5 representantes peruanos al Parlamento Andino: funciones, requisitos, competencias del organismo internacional y proceso de elección específico.', attachments: ['/docs/parlamento_andino_2026.pdf'], language: 'es', published_at: '2025-11-10', source_url: 'https://eg2026.onpe.gob.pe/parlamento-andino', parsed_hash: 'hash-guide-andino' },
  { id: 6, title: 'Miembros de mesa - Manual completo', body: 'Manual integral para miembros de mesa: instalación, procedimientos durante la votación, cierre de mesa, llenado de actas, manejo de incidencias y responsabilidades legales. Incluye formatos y documentos oficiales.', attachments: ['/docs/manual_miembros_mesa_2026.pdf'], language: 'es', published_at: '2025-11-12', source_url: 'https://eg2026.onpe.gob.pe/miembros-mesa', parsed_hash: 'hash-guide-mesa' }
]

export const MOCK_PROVENIENCIA = [
  { id:1, fuente: 'ONPE', raw_payload: {example:true}, parsed_hash: 'mockhash1', source_url:'https://www.onpe.gob.pe', fetched_at: new Date().toISOString() }
]

export const MOCK_AUDIT = [
  { id:1, resource_type: 'candidato', resource_id: 1, action: 'created', note: 'Imported from ONPE feed', created_at: new Date().toISOString() }
]

export const MOCK_INCIDENTS = []
